project:
  title: "temp_website"
  output-dir: docs

website:
  title: "Joseph Website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left